#background {
#	monitor = path = /home/bielimmeral/Imagens/wallpapers/Immeral60.png
#	blur_passes = 2
#	blur_size = 4
#}

input-field {
	monitor = size = 250,50
	outline_thickness = 3
	outer_color = rgb(150, 0, 24)
	inner_color = rgba(13, 13, 13, 0.9)
	font_color = rgb(255, 132, 120)
	placeholder_text = <i>Digite a senha...</i> 
	fail_color = rgb(255, 0, 0)
	position = 0, -20
	halign = center
	valign = center
}

label {
	monitor = text = Olá, $USER 
	color = rgb(255, 132, 120)
	font_size = 25
	position = 0, 100
	halign = center
	valign = center
}

