# include kitty-colors.conf
include dark-theme.auto.conf

background_opacity 1.0
background_blur 1

font_size 10

cursor_text_color #960018
cursor_shape underline
cursor_shape_unfocused hollow
cursor_blink_interval -1

cursor_trail 1
cursor_trail_decay 0.1 0.3
cursor_trail_color #960018


#include current-theme.conf
